# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Battle talks
tagline:          'A Jekyll theme'
description:      'Battle rap graphics'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

theme: tale
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
